config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  resources :mugs
  resources :profiles
  resources :images
  root :to => 'mugs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/extra_data.rb
class ExtraData < ApplicationRecord
end

app/models/hug.rb
class Hug < ApplicationRecord
    belongs_to :profile
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :profile 
    has_one_attached :image
    
end

app/models/mug.rb
class Mug < ApplicationRecord

    belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_many :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @profile  = Profile.find current_user.id 
    @images = @profile.images

   
  end

  def show
  end

 

  def update
  end

  def new
    @profile = Profile.find current_user.id
    @image = @profile.images.build

  end

  def create
    @profile = Profile.find current_user.id
    @image = @profile.images.build (image_params)
    @image.save
    redirect_to images_path
  end

  def edit
  end

  def delete
  end

  private 
  def image_params 
    params.require(:image).permit(:subtitle,:file,:public,:image)
  end
  
end

app/controllers/mugs_controller.rb
class MugsController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def update
  end

  def delete
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user

  def index
    @profiles = Profile.last
    @ni = @profiles.name.chars
   
  end

  def show
  end

  def new
    @user = User.find current_user.id
    @profile = @user.build_profile
  end

  def create
    @user = User.find current_user.id
    @profile = @user.build_profile(profile_params.except("multiplier"))
    @profile.multiplier = profile_params[:multiplier].join
    @profile.save
  end

  def update
  end

  def edit
  end

  def delete
  end

  private 

  def profile_params 
    params.require(:profile).permit(:name,:ocupation,:bio,{multiplier:[]})

  end 



end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
   new_profile_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/mugs_helper.rb
module MugsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/images/delete.html.haml
%h1 Images#delete
%p Find me in app/views/images/delete.html.haml

app/views/images/edit.html.haml
%h1 Images#edit
%p Find me in app/views/images/edit.html.haml

app/views/images/index.html.haml
.container
  .row.mt-5
    .col-sm-12.text-right.p-0
      .btn.button_home_color
        = link_to('agregar', new_image_path)
    .card.mt-3
      .card-header
        imagenes
      .card-body
        - @images.each do |image|  
          .row.mt-3.border-top.p-4
            .col-sm-2
              = image_tag url_for(image.image), alt: '', height: '80%', width: '80%', class: 'image_thumbnail'  
            .col-sm-10
              =image.subtitle
                

app/views/images/new.html.haml
.wrapper.ml-3
  .container
    %h1 Agregar imagen 
    = form_for @image do |f|
      .row
        .col-sm-4
          %strong
            =f.label :image
          %p Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt, quidem possimus 
        .col-sm-8
          .card
            .card-header 
              imagen principal
            .card-body
              =f.file_field :image, class: "dropify"
      .row.mt-3
        .col-sm-4
          %strong
            =f.label :subtitle
          %p Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt, quidem possimus
        .col-sm-8
          .card
            .card-header
              subitulo
            .card-body        
              =f.text_field :subtitle, class: "form-control"
              .col-sm-12.mt-2.p-0
                =f.check_box :public
                =f.label "mostrar esta imagen en tu perfil"
              
          =f.submit "guardar foto", class: "float-right mt-5"
         
            

app/views/images/show.html.haml
%h1 Images#show
%p Find me in app/views/images/show.html.haml

app/views/images/update.html.haml
%h1 Images#update
%p Find me in app/views/images/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AC
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'

  %body
    %nav.navbar.navbar-light.nav_color_light.p-0.nav
      .col-2.no-gutters.p-0
        .nav-item.nav_color_dark.center.font_white_color.nav-item
          %a.navbar-brand.p-2
            A&C
      .col-8
        .nav-item.center.border-danger.font_white_color.nav-item.nav_color_mpink
          %a.navbar-brand
            hola
      .col-2.no-gutters.p-0
        .nav-item.border-left.border-danger.text-right.font_white_color.nav-item
          %a.navbar-brand.p-2
            Romer Ramos

      

  - if notice
    %p.alert.alert-success
      = notice

  - if alert
    %p.alert.alert-danger
      = alert
      
  .row.no-gutters.h-100
    .col-sm-2.border-right
      %na.navbar
        %ul.navbar-nav
          %li.nav-item
            = link_to "perfil","#", class: "nav-link"
          %li.nav-item    
            = link_to "imágenes",images_path,class: "nav-link"
          %li.nav-item
            = link_to "cuentas","#", class: "nav-link"

    .col-sm-10
      = yield

app/views/layouts/mugs.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AC
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    <link href="https://fonts.googleapis.com/css?family=Happy+Monkey" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">  
  %body
    %nav.navbar.navbar-expand-xs.navbar_color_white.shadow-sm.p-0
      .nav-item.ml-4.brand_background_color.p-2
        A&C
      .nav-item.p-3.mr-3.login_border_color
        Login
    .col-xs-12.text-center.p-4
      = image_tag "coffees.svg" 
    .col-xs-12.text-center.mt-3.title_font
      Un café es un abrazo atrapado en una taza
    .col-xs-12.text-center.mt-5.subtitle_font
      Recibe aprecio y gratitud mediante donaciones online
    .col-xs-12.text-center.mt-5
      %button.btn.button_home_color
        = link_to 'crear mi perfil',new_user_registration_path
        
  

app/views/mugs/create.html.haml
%h1 Mugs#create
%p Find me in app/views/mugs/create.html.haml

app/views/mugs/delete.html.haml
%h1 Mugs#delete
%p Find me in app/views/mugs/delete.html.haml

app/views/mugs/index.html.haml
%h1 Mugs#index
%p Find me in app/views/mugs/index.html.haml

app/views/mugs/show.html.haml
%h1 Mugs#show
%p Find me in app/views/mugs/show.html.haml

app/views/mugs/update.html.haml
%h1 Mugs#update
%p Find me in app/views/mugs/update.html.haml

app/views/profiles/create.html.haml
%h1 Profiles#create
%p Find me in app/views/profiles/create.html.haml

app/views/profiles/delete.html.haml
%h1 Profiles#delete
%p Find me in app/views/profiles/delete.html.haml

app/views/profiles/edit.html.haml
%h1 Profiles#edit
%p Find me in app/views/profiles/edit.html.haml

app/views/profiles/index.html.haml
= @ni.class

app/views/profiles/new.html.haml
.wrapper.ml-3
  .container
    .row.mt-5
      .col-sm-12
        %h1 Perfil de Usuario
      .col-sm-8.mt-5
        .card
          .card-body
            = form_for @profile do |f|
              .row
                .col-sm-6
                  = f.label :nombre
                  = f.text_field :name, class: "form-control"
                .col-sm-6
                  = f.label :ocupation
                  = f.text_field :ocupation, class: "form-control"
                .col-sm-12
                  = f.label "biografia"
                  = f.trix_editor :bio, class: "form-control" 
              </div></div></div>
              .col-sm-4.mt-5
                .card
                  .card-body
                    .row    
                      .col-sm-12
                        = f.label "Monto de un Café"
                        = f.text_field :donation_amount, class: "form-control"
                      .col-sm-12
                        = f.label "simbolo de la moneda"
                        = f.text_field :currency, class: "form-control"
                      .col-sm-12
                        = f.label :multipler
                      .col-sm-3
                        <input type="text" name="profile[multiplier][]" class="form-control input_rounded"/>
                      .col-sm-3
                        <input type="text" name="profile[multiplier][]" class="form-control input_rounded"/>
                      .col-sm-3  
                        <input type="text" name="profile[multiplier][]" class="form-control input_rounded"/>
                      .col-sm-3
                        <input type="text" name="profile[multiplier][]" class="form-control input_rounded"/>
                .col-sm-1.offset-7.mt-5
                  = f.submit class: "btn btn-secondary button_color_pink"

app/views/profiles/show.html.haml
%h1 Profiles#show
%p Find me in app/views/profiles/show.html.haml

app/views/profiles/update.html.haml
%h1 Profiles#update
%p Find me in app/views/profiles/update.html.haml

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>